---
title: "lnc_RNA_normalizado(TyP)"
author: "Josu Lecuona"
date: "2023-02-21"
output: html_document
---

##Cargar y filtrar solo los genes que sean lnc_RNA.
```{r}
setwd("C:\\Users\\MI\\Desktop\\MASTER\\TFM\\NASIR\\lnc_RNA")
library(tidyverse)

lnc_RNA <- read.csv2("lnc_RNA.csv", header = TRUE)
##NASIR_T_P sin genes duplicados
setwd("C:\\Users\\MI\\Desktop\\MASTER\\TFM\\NASIR\\NASIR_T_P(normalizados)")
NASIR_T_P <-read.csv2("NASIR_T_P_NORMALIZED(BIEN).csv", header = TRUE)

##Eliminamos columna 2
lnc_RNA[,2] <- NULL


## Hacemos un inner join para que solamente tengamos los reads de long non coding.
l_non_coding <- merge(x = NASIR_T_P, y = lnc_RNA, by = c("X"))

## Le asigno como una variable con el nombre G  a la columna de gene
G <- l_non_coding$X

##A la tabla de NASIR le quito la columna de gene. 
l_non_coding<- l_non_coding%>%
  select(-X)

## Los nombres de los genes los meto como si fuera una variable de esta manera
## diferenciandose de los numeros
rownames(l_non_coding) <- G
```


## Filtros de los genes.
```{r}
                                         
detect<-apply(l_non_coding, 2, function(x){as.numeric(as.character(x))})## 2 hace referencia a las columnas, 
##pasamos todas las columnas a numericas
detect <- as.data.frame(detect)
suma_gen <- rowSums(detect)
l_non_coding <- cbind(l_non_coding, suma_gen)

l_non_coding <- l_non_coding %>% 
  filter(suma_gen > 0)

quantile(l_non_coding$suma_gen, 0.25)

##Quitamos aquellos genes que tengan menor o igual que el cuantil 0.25. . 

l_non_coding <- l_non_coding %>% 
  filter(suma_gen > 3.54)

## Quitamos aquellos genes que no tengean en por lo menos 5 pacientes el treshold
for (fila in 1:nrow(l_non_coding)){
  suma_pacientes <-  0
  for (columna in 1:43){
    if (l_non_coding[fila,columna] < 3.53){
      suma_pacientes <- suma_pacientes + 1
    }}
  if (suma_pacientes > 38){
    l_non_coding[fila, 44] <- 0
  } else{
    l_non_coding[fila, 44] <- 1
  }
}

l_non_coding <- l_non_coding %>% 
  filter(suma_gen == 1)


##Quitar columna suma_gen
l_non_coding$suma_gen <- NULL

sd_lnc <- data.frame()

##Hacer sd de cada gen

for (fila in 1:nrow(l_non_coding)){
  sd <- sd(l_non_coding[fila,])
  sd_lnc <- rbind(sd_lnc, sd) 
}

##Unir las desviaciones estandar de cada gen 
l_non_coding<- cbind(l_non_coding, sd_lnc)

summary(sd_lnc)

## Quitar los que tengan desviacion estandar menor que el 1 cuartil de todas las desviaciones 
l_non_coding <- l_non_coding %>% 
  filter(sd_lnc > 4.932)

write.csv(l_non_coding, "lnc_RNA_filtrado.csv")

```


